export const GET_LIST_CINEMA = "GET_LIST_CINEMA";
export const GET_LIST_DETAIL_CINEMA = "GET_LIST_DETAIL_CINEMA";
export const GET_INFO_DETAIL_CINEMA = "GET_INFO_DETAIL_CINEMA";
export const GET_ROOM_TICKET = "GET_ROOM_TICKET";
