export const GET_LIST_CINEMA = "GET_LIST_CINEMA";
export const GET_LIST_DETAIL_CINEMA = "GET_LIST_DETAIL_CINEMA";
export const GET_INFO_DETAIL_CINEMA = "GET_INFO_DETAIL_CINEMA";
export const GET_ROOM_TICKET = "GET_ROOM_TICKET";
export const GET_LIST_LOGIN = "GET_LIST_LOGIN";
export const ACT_BOOKING_TICKET = "ACT_BOOKING_TICKET";
export const GET_LOAI_NGUOI_DUNG = "GET_LOAI_NGUOI_DUNG";
